### ISSUE TITLE
rpcbind is not enabled

### ISSUE THREAD

**Issue by lameventanas** [cloudfoundry/nfsv3driver#28]
When I restage my app to use an nfs service, the mount fails.
If I ssh to the VM and start rpcbind manually via `/etc/init.d/rpcbind start`, it works.
Shouldn't this service be enabled by nfsv3driver?

**Comment by lameventanas** [comment]
Note: this is using nfs version 3.

**Comment by julian-hj** [comment]
Hi @lameventanas 

I gather that you're using bosh-lite, for which this is a [known issue](https://github.com/cloudfoundry/nfs-volume-release#bosh-lite-deployments).

What we have seen is that:
1. For production stemcells (vsphere, GCP, AWS, Azure), it is not necessary to start rpcbind, as it is already running
1. For some customers, having rpcbind running is deemed to be a [security risk](https://security.stackexchange.com/questions/80799/security-risk-of-opening-port-111-rpcbind), so we prefer not to add scripting to start it, in case customers are deliberately disabling it.

**Comment by julian-hj** [comment]
Hi again @lameventanas I'm going to go ahead and close this issue, but if you are still stuck, you might consider creating a tiny bosh release that has a job in it that only starts up rpcbind in the `pre-start` step.  You can use the bosh `init-release` and `generate-job` commands to quickly bootstrap a bosh release directory. From there you would just need to create a small script to start up rpcbind.

Cheers,
-Julian
